<footer>
	<div class="footer-container">
	   <div class="footer">
	       <div class="footer-heading footer-1">
		       <h2>About Us</h2>
			   <a href="#">Blog</a>
			   <a href="#">Demo</a>
			   <a href="#">Customers</a>
			   <a href="#">Investors</a>
			   <a href="#">Terms of Service</a>
		   </div>
		   <div class="footer-heading footer-2">
		       <h2>Contact Us</h2>
			   <a href="#">Jobs</a>
			   <a href="#">Support</a>
			   <a href="#">Contact</a>
			   <a href="#">Sponsorships</a>
			   
		   </div>
		   <div class="footer-heading footer-3">
		       <h2>Social Media</h2>
			    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
			   <a href="#" class="fa fa-instagram">: Instagram</a>
              <a href="#" class="fa fa-facebook">: Facebook</a>
              <a href="#" class="fa fa-twitter">: Twitter</a>
			  <a href="#" class="fa fa-linkedin">: LinkedIn</a>
			  <a href="#" class="fa fa-youtube">: YouTube</a>
			  
		   </div>
		   <div class="footer-email-form">
		      <h2>Join Our Newsletter</h2>
			  <input type="email" placeholder="Enter Your Email" id="footer-email">
			  <input type="submit" value="Sign Up" id="footer-email-btn">
	     </div>
	  </div>
	</div>
	  </footer>