 <header>
   <a href="images/ishtv2.png"><img src="images/ishtv2.png" alt="ishTV logo" class="logo"/></a>
      <h1 class="h1">ishTV - Connecting You</h1> 
	  
	  <hr>
	  
	  <!-- Menu Bar -->
	  
	  <nav>
	    <ul class="menu">
		 
		<li> <a href="index.php">Home</a></li>
		<li> <a href="product.php">Description</a></li>
		<li> <a href="enquire.php">Enquiry</a></li>
		<li> <a href="manager.php">Manage</a></li>
		<li> <a href="about.php">About</a></li>
		<li> <a href="enhancements2.php">Enhancements 2</a></li>
		<li> <a href="enhancements3.php">Enhancements 3</a></li>
		
		</ul>	  
	  </nav>  <hr>
	  </header>